import random

def obtener_saludo(nombre):
    saludos = [
        "¡Hola {name}, espero que tu código esté libre de bugs hoy!",
        "¡{name} ha entrado al chat! ¡Que los bugs te sean leves!",
        "¡Bienvenido {name}! ¿Has probado apagarlo y encenderlo?",
        "¡Hey {name}, cuidado con los errores fuera de índice!",
        "¡Saludos {name}! ¿Otro día, otro script?",
        "¡{name} ha llegado! Recuerda: la vida es corta, usa Python.",
        "¡Hola {name}, el 10% de programar es escribir código, el 90% es encontrar el bug!",
        "¡Bienvenido {name} al mundo donde las tabulaciones y espacios en blanco importan!",
        "¡Que la fuerza de Python esté contigo, {name}!",
        "¿Has abrazado a tu serpiente hoy, {name}?",
        "¡Hey {name}! Recuerda: las excepciones no se capturan, se manejan.",
        "¡Hola {name}! ¿Listo para debuggear?",
        "¡Bienvenido {name}, donde las referencias de Monty Python abundan!",
        "¡Hey {name}, recuerda guardar tus cambios antes que todo explote!",
        "¡Saludos {name}! Espero que tus paréntesis estén balanceados.",
        "¡{name} ha entrado al chat! Recuerda, ¡La vida es mejor sin errores de sintaxis!",
        "¡Hola {name}! No seas un punto y coma en la vida de alguien.",
        "¡Bienvenido {name}, donde todo es objeto!",
        "¡Hey {name}, espero que tu día sea más agradable que una fusión de código!",
        "¡Hola {name}, que no se te escape ninguna excepción hoy!",
        "¡Bienvenido {name} al mundo donde el pato hace 'cuak'!",
        "¡Hey {name}, evita los loops infinitos!",
        "¡Saludos {name}, may the --force be with you!",
        "¡{name} ha llegado! Recuerda: ¡Los comentarios son tus amigos!",
        "¡Hola {name}, ten cuidado con las serpientes!",
        "¿Has venido a programar o a desplegar, {name}?",
        "¡{name}, deja la herencia y únete a la composición!",
        "¡Hey {name}, que tus bugs se conviertan en features!",
        "¡{name}, piensa en Python y la respuesta te será revelada!",
        "¡Hola {name}, cuidado con los bordes afilados de los arrays!",
        "¡Bienvenido {name}! Recuerda: ¡Los espacios en blanco importan!",
        "¡Hey {name}, no te olvides del zen de Python!",
        "¡Hola {name}, Python te elige!",
        "¡{name}, donde las list comprehensions son arte!",
        "¡Bienvenido {name} al reino del duck typing!",
        "¡Hey {name}, nunca te enfrentes a un bug enojado!",
        "¡{name}, en este chat usamos Python, no parloteamos como las serpientes!",
        "¡Hola {name}! ¡Pythonic way o nada!",
        "¡Bienvenido {name}, solo los valientes manejan excepciones!",
        "¡Hey {name}, cuidado con el GIL!",
        "¡{name} ha entrado! ¡Pero no uses GOTO, por favor!",
        "¡Hola {name}, nunca subestimes el poder de un buen decorator!",
        "¡{name}, aquí amamos a las serpientes, pero más a Python!",
        "¡Bienvenido {name}! PEP 8 por vida.",
        "¡Hey {name}, la recursión es amiga, no comida!",
        "¡{name}, espero que tu día sea tan brillante como un IDE oscuro!",
        "¡Hola {name}, a veces en la vida, tienes que pasar por un garbage collector!",
        "¡Bienvenido {name}! Aquí, las serpientes tienen la última palabra.",
        "¡Hey {name}, mantén tus funciones puras y tu código limpio!",
        "¡Hola {name}! ¡Un día sin Python es un día perdido!",
        "¡{name}, donde lambda no es solo una letra griega!",
        "¡Bienvenido {name}, aquí valoramos los closures!",
        "¡Hey {name}, que tus tuplas sean inmutables y tus listas dinámicas!",
        "¡Hola {name}, a veces en la vida, todos somos un poco `None`!",
        "¡{name}, espero que no tengas miedo de las serpientes!",
        "¡Bienvenido {name} al ciber-espacio Pythonic!",
        "¡Hola {name}, mantente DRY y sigue codificando!",
        "¡{name}, donde los errores son solo una forma de aprender!",
        "¡Hey {name}, ¿pronto será hora del tea-time refactoring?",
        "¡Bienvenido {name}! ¡Que la serpiente te guíe!",
        "¡Hola {name}, mantente Pythonic!",
        "¡{name}, recuerda: ¡todo es un objeto!",
        "¡Hey {name}, la indentación es la clave!",
        "¡Hola {name}, que el garbage collector esté contigo!",
        "¡{name}, que tus asserts siempre sean verdaderos!",
        "¡Bienvenido {name}, aquí Python es el rey!",
        "¡Hey {name}, ¿estás listo para un viaje geek?",
        "¡Hola {name}, no importa cuántos errores tengas, aquí todos aprendemos!",
        "¡{name}, siempre hay tiempo para un refactor!",
        "¡Bienvenido {name}, espero que no tengas fobia a las serpientes!",
        "¡Hey {name}, mantente alejado de los side-effects!",
        "¡{name}, recuerda importar solo lo que necesitas!",
        "¡Hola {name}, la mejor herramienta para el trabajo es Python!",
        "¡{name}, que tus días sean tan consistentes como tus identaciones!",
        "¡Hey {name}, siempre hay una biblioteca para eso!",
        "¡Bienvenido {name}, espero que tu pip nunca se rompa!",
        "¡Hola {name}, que tus variables sean siempre descriptivas!",
        "¡{name}, no importa cuántos errores encuentres, siempre hay una solución!",
        "¡Hey {name}, no te olvides de hacer commit!",
        "¡Hola {name}, siempre hay una luz al final del tunnel de debugging!",
        "¡{name}, ¿listo para desentrañar el próximo misterio de código?",
        "¡Bienvenido {name}, que tus funciones sean cortas y tus nombres largos!",
        "¡Hola {name}, ¡aquí las serpientes no muerden!",
        "¡{name}, ¿estás listo para el próximo challenge?",
        "¡Hey {name}, no te preocupes por los bugs, son solo una característica no documentada!",
        "¡Hola {name}, que tu código siempre sea Pythonic!",
        "¡{name}, ¡sigue codificando y nunca te rindas!",
        "¡Bienvenido {name}, siempre hay algo nuevo que aprender en Python!",
        "¡Hola {name}, que la PEP 8 te guíe!",
        "¡{name}, ¡aquí las serpientes son amigas, no comida!",
        "¡Hey {name}, ¡sigue soñando en Python!",
        "¡Hola {name}, ¡espero que nunca te encuentres con un Python furioso!",
        "¡{name}, siempre es un buen momento para aprender algo nuevo!",
        "¡Bienvenido {name}, ¡aquí amamos a las serpientes y a los geeks por igual!",
        "¡Hola {name}, ¡espero que nunca te encuentres con un IndexError!",
        "¡{name}, ¡mantente geek y sigue codificando!",
        "¡Hey {name}, ¡cuida tus identaciones y todo irá bien!",
        "¡Hola {name}, que la fuerza del código abierto esté contigo!"
    ]
    
    return random.choice(saludos).format(name=nombre)