import random

def obtener_alcohol_solo(nombre):
    TOMAR_SOLO = [
        f"{nombre} se cree pirata, se tomó todo el ron solo.",
        f"{nombre} dijo que el whisky era su 'agua', y no dejó ni una gota.",
        f"¿Vino? ¿Qué vino? {nombre} se lo tomó todo.",
        f"{nombre} pensó que la cerveza era jugo. Adiós pack de seis.",
        f"Buscando el 'espíritu' del agave, {nombre} acabó con el tequila.",
        f"{nombre} hizo desaparecer el vodka. ¡Debe ser mago!",
        f"{nombre} probó el gin y decidió que no quería compartir.",
        f"Para {nombre}, el brandy era solo una 'probada'. Pero, ¡sorpresa! Se lo terminó.",
        f"¡Alerta! {nombre} se creyó realeza y se tomó todo el cognac.",
        f"¿Sake? {nombre} pensó que era un ritual y se lo tomó todo.",
        f"{nombre} y el pisco tuvieron una cita. Spoiler: no dejó nada para los demás.",
        f"Creo que {nombre} pensó que el champagne era agua con gas... No queda nada.",
        f"¡Se busca! {nombre} robó y bebió todo el licor de café.",
        f"{nombre} hizo un 'brindis personal' y acabó con el vermut.",
        f"Si ves a {nombre} bailando solo, es porque se tomó todo el mojito.",
        f"{nombre} dijo que se sentía como en un Western, y desapareció el bourbon.",
        f"Buscábamos la sangría y... ¡sorpresa! {nombre} la convirtió en su cóctel personal.",
        f"{nombre} preguntó si la sidra era refresco. Ahora sabemos que no.",
        f"El baile de {nombre} tiene explicación: se tomó todo el absenta.",
        f"¡Peligro! {nombre} descubrió el amaretto y no quedó ni una gota.",
        f"{nombre} se fue a 'explorar' y regresó sin el mezcal.",
        f"¿Alguna vez has visto a un dragón? {nombre} se tomó todo el licor de hierbas y ahora cree que es uno.",
        f"{nombre} se tomó el Bailey's. ¡Dijo que era para su café!",
        f"La limoncello desapareció. Sí, {nombre} está haciendo caras chistosas ahora.",
        f"Si {nombre} brilla en la oscuridad, es porque se tomó todo el licor de kiwi.",
        f"¡Sorpresa! El martini se volvió invisible... con ayuda de {nombre}.",
        f"{nombre} quiso viajar a Italia con el grappa. No sobró ni una gota.",
        f"El campari se fue de campamento con {nombre}. No regresó.",
        f"{nombre} intentó 'cocinar' y terminó con todo el vino de cocina.",
        f"¿Oyen ese ruido? Es {nombre} que se tomó todo el licor de lychee y ahora canta.",
        f"¿Dónde está el Jägermeister? En el estómago de {nombre}, por supuesto.",
        f"{nombre} buscó a la 'pantera rosa' y se tomó todo el rosado.",
        f"{nombre} se tomó el malibú. Ahora espera las olas del mar en el sofá.",
        f"El anís estrellado brilló por última vez en la copa de {nombre}.",
        f"¡Alerta de calor! {nombre} tomó todo el licor de chile.",
        f"El licor de huevo se convirtió en el desayuno exclusivo de {nombre}.",
        f"¿Buscas el calvados? {nombre} ya hizo un brindis en su honor.",
        f"¡Cuidado! {nombre} y el cointreau hicieron un pacto y no queda nada.",
        f"{nombre} se cree Sherlock y se tomó todo el porter.",
        f"{nombre} quería calentarse y se tomó todo el licor de canela.",
        f"¡Fiesta de burbujas! Pero {nombre} se tomó todo el prosecco.",
        f"{nombre} buscó fortuna y terminó con el licor de oro.",
        f"El chianti tuvo una cena romántica con {nombre}. No volvió.",
        f"{nombre} dice que el ouzo le ayuda a pensar. ¡Por eso no queda!",
        f"El licor de chocolate es el nuevo postre favorito de {nombre}.",
        f"{nombre} se fue a 'pescar' y volvió sin el aquavit.",
        f"{nombre} dice que el rumple minze es su chicle. ¡Se lo tomó todo!",
        f"El tinto de verano tuvo un 'invierno' largo en el estómago de {nombre}.",
        f"¡Aventura espacial! {nombre} se tomó todo el licor de galaxia.",
        f"{nombre} quiso hacer magia y se desvaneció el licor de unicornio.",
        f"{nombre} creyó que era un chef y se llevó todo el mirin.",
        f"¿Buscas el licor de plátano? {nombre} dice que se lo llevó un mono.",
        f"El marsala se embarcó en un viaje... directo al estómago de {nombre}.",
        f"{nombre} jugó al escondite con el limoncino. Spoiler: Lo encontró y se lo tomó.",
        f"El curaçao azul tuvo un 'accidente' con {nombre}. Ahora él luce un poco azul.",
        f"{nombre} se fue en busca de sus raíces y se tomó todo el licor de agave.",
        f"El triple sec se volvió doblemente invisible gracias a {nombre}.",
        f"¿Dónde está el claret? {nombre} lo 'investigó' a fondo.",
        f"{nombre} se fue a una 'degustación' y no dejó nada de la crema de menta.",
        f"¡Misterio resuelto! {nombre} fue quien se tomó el licor de misterio.",
        f"El licor de manzana no resistió la tentación de {nombre}. Ahora brilla en su interior.",
        f"La crema de almendra encontró un nuevo hogar. ¡Gracias, {nombre}!",
        f"El sherry se fue de paseo con {nombre}. Dudo que vuelva.",
        f"{nombre} se creyó astronauta y se tomó todo el licor espacial.",
        f"{nombre} buscó el 'tesoro' y acabó con el ron dorado.",
        f"¡Emergencia! El bitter se volvió dulce en manos de {nombre}.",
        f"{nombre} dice que el pastis es su té de la tarde. Así que... no queda.",
        f"El licor de melón maduró rápidamente con {nombre}. No esperes encontrarlo.",
        f"{nombre} se llevó el licor de fresa para su 'postre'.",
        f"¿Alguien vio el cassis? Oh, espera... {nombre} lo 'vio' primero.",
        f"El kirsch decidió 'echar raíces' en {nombre}. ¡Adiós cerezas!",
        f"El oude se volvió 'nuevo' en el paladar de {nombre}.",
        f"{nombre} intentó 'refrescarse' y acabó con el licor de menta.",
        f"{nombre} hizo un 'experimento' y transformó el licor de laboratorio.",
        f"El licor de vainilla se convirtió en el aroma principal de {nombre}.",
        f"El grappa quiso hacer una gira. {nombre} fue su última parada.",
        f"¡Descubrimiento! El licor de explorador fue 'explorado' por {nombre}.",
        f"{nombre} se llevó el licor de durazno para su picnic personal.",
        f"El licor de huevo pensó que era Pascua con {nombre}. ¡Sorpresa! No regresó.",
        f"{nombre} y el licor de coco se fueron a la playa. Solo regresó {nombre}.",
        f"El licor de caramelo endulzó el día de {nombre}. No queda ni una gota.",
        f"{nombre} dice que el armagnac es su elixir mágico. ¡Por eso desapareció!",
        f"¡Aventura medieval! {nombre} se llevó el licor de castillo.",
        f"El licor de arroz se convirtió en el 'snack' favorito de {nombre}.",
        f"{nombre} hizo un pacto con el licor demoníaco. ¡No queda nada en la botella!",
        f"El licor tropical decidió 'broncearse' en el estómago de {nombre}.",
        f"{nombre} se creyó vikingo y acabó con el licor nórdico.",
        f"El licor de pera encontró un árbol en el corazón de {nombre}. ¡No regresará!",
        f"{nombre} quiso hacer una 'ensalada' y se llevó el licor de frutas.",
        f"El licor de chocolate blanco se 'derretió' gracias a {nombre}."
    ]
    return random.choice(TOMAR_SOLO)

def obtener_invitar_alcohol(invitador, invitado):
    INVITAR_ALCOHOL  = [
        f"{invitador} le invita a tomar vino a {invitado}",
        f"{invitador} le ofrece un shot de tequila a {invitado}",
        f"{invitador} quiere brindar con champagne junto a {invitado}",
        f"{invitador} propone un gin tonic para compartir con {invitado}",
        f"{invitador} le pasa una cerveza fría a {invitado}",
        f"{invitador} le sirve un vaso de whisky a {invitado}",
        f"{invitador} decide compartir su botella de ron con {invitado}",
        f"{invitador} le pregunta a {invitado} si quiere un poco de cognac",
        f"{invitador} le ofrece a {invitado} una copa de brandy",
        f"{invitador} piensa que un mojito sería perfecto para {invitado}",
        f"{invitador} sugiere que {invitado} pruebe el pisco sour que preparó",
        f"{invitador} le sirve a {invitado} un cóctel misterioso",
        f"{invitador} quiere que {invitado} deguste su sake favorito",
        f"{invitador} invita a {invitado} a probar un licor de café especial",
        f"{invitador} cree que una margarita alegraría la noche de {invitado}",
        f"{invitador} le da a {invitado} una probada de su vodka premium",
        f"{invitador} piensa que un bloody mary es la elección de {invitado}",
        f"{invitador} le sugiere a {invitado} que pruebe el licor de hierbas",
        f"{invitador} le ofrece a {invitado} una copa de su vermut especial",
        f"{invitador} quiere que {invitado} se relaje con un poco de amaretto",
        f"{invitador} invita a {invitado} a disfrutar de un buen Jägermeister",
        f"{invitador} le sirve a {invitado} un delicioso cosmo",
        f"{invitador} quiere compartir un momento con {invitado} y un buen licor de melón",
        f"{invitador} piensa que un daiquiri sería del gusto de {invitado}",
        f"{invitador} le da a {invitado} un shot de absenta",
        f"{invitador} le ofrece a {invitado} un poco de licor de chocolate",
        f"{invitador} le invita a {invitado} un cóctel exótico",
        f"{invitador} sugiere que {invitado} pruebe su mezcal artesanal",
        f"{invitador} le sirve a {invitado} un chupito de licor de fresa",
        f"{invitador} le ofrece a {invitado} una caipirinha refrescante",
        f"{invitador} quiere que {invitado} deguste un buen bourbon",
        f"{invitador} invita a {invitado} a brindar con un poco de ouzo",
        f"{invitador} le pasa a {invitado} una copa de licor de plátano",
        f"{invitador} le sirve a {invitado} un delicioso aperol spritz",
        f"{invitador} invita a {invitado} a disfrutar de un bellini al atardecer",
        f"{invitador} quiere que {invitado} pruebe su sidra artesanal",
        f"{invitador} le da a {invitado} una probada de su licor de kiwi",
        f"{invitador} le ofrece a {invitado} una copa de campari",
        f"{invitador} invita a {invitado} a probar un poco de licor de almendra",
        f"{invitador} le sugiere a {invitado} que pruebe el licor de huevo",
        f"{invitador} cree que un martini es la elección perfecta para {invitado}",
        f"{invitador} le da a {invitado} un shot de licor de durazno",
        f"{invitador} quiere que {invitado} pruebe su crema de whisky casera",
        f"{invitador} piensa que un mimosa alegraría la mañana de {invitado}",
        f"{invitador} le invita a {invitado} un poco de licor de vainilla",
        f"{invitador} le sugiere a {invitado} que pruebe su cerveza artesanal",
        f"{invitador} invita a {invitado} a brindar con un poco de sangría",
        f"{invitador} le sirve a {invitado} un chupito de licor de manzana",
        f"{invitador} le ofrece a {invitado} un cocktail tropical",
        f"{invitador} quiere que {invitado} disfrute de un old fashioned",
        f"{invitador} invita a {invitado} a relajarse con un poco de grappa",
        f"{invitador} le da a {invitado} una probada de su licor de cereza",
        f"{invitador} cree que un tom collins refrescaría a {invitado}",
        f"{invitador} le sugiere a {invitado} que pruebe su limoncello",
        f"{invitador} invita a {invitado} a un viaje tropical con su piña colada",
        f"{invitador} quiere compartir un momento con {invitado} y un buen cointreau",
        f"{invitador} invita a {invitado} a disfrutar de un negroni clásico",
        f"{invitador} le da a {invitado} un shot de licor de caramelo",
        f"{invitador} le sirve a {invitado} un delicioso punch tropical",
        f"{invitador} piensa que un white russian sería perfecto para {invitado}",
        f"{invitador} invita a {invitado} a viajar a Escocia con un buen scotch",
        f"{invitador} le da a {invitado} una probada de su licor de menta",
        f"{invitador} quiere que {invitado} pruebe su brandy de manzana",
        f"{invitador} invita a {invitado} a probar un poco de licor de mora",
        f"{invitador} le sugiere a {invitado} que pruebe el licor de coco",
        f"{invitador} quiere que {invitado} deguste un buen bitter",
        f"{invitador} le ofrece a {invitado} una copa de malibu",
        f"{invitador} piensa que un dark and stormy es la elección de {invitado}",
        f"{invitador} quiere compartir un cuba libre con {invitado}",
        f"{invitador} invita a {invitado} a disfrutar de un buen brandy de pera",
        f"{invitador} le da a {invitado} una probada de su licor de café especial",
        f"{invitador} le ofrece a {invitado} un poco de licor de huevo casero",
        f"{invitador} invita a {invitado} a probar su especialidad: licor de chili",
        f"{invitador} quiere que {invitado} pruebe su receta secreta de licor de arándanos",
        f"{invitador} piensa que un espresso martini despertaría a {invitado}",
        f"{invitador} invita a {invitado} a viajar al Caribe con un buen ron especiado",
        f"{invitador} le sugiere a {invitado} que pruebe su licor de naranja casero",
        f"{invitador} le ofrece a {invitado} un cocktail con un toque de licor de almendra",
        f"{invitador} quiere compartir un momento con {invitado} y un buen amaro",
        f"{invitador} invita a {invitado} a probar su cóctel de licor de maracuyá",
        f"{invitador} piensa que un fizz de gin sería del gusto de {invitado}",
        f"{invitador} le ofrece a {invitado} un poco de licor de grosella",
        f"{invitador} invita a {invitado} a un brindis con su licor de miel casero",
        f"{invitador} le sugiere a {invitado} que pruebe su licor de higo especial",
        f"{invitador} quiere que {invitado} deguste su receta secreta de licor de cacto",
        f"{invitador} invita a {invitado} a relajarse con un cóctel de licor de ciruela",
        f"{invitador} le da a {invitado} una probada de su licor de regaliz especial",
        f"{invitador} le ofrece a {invitado} una copa de su aperitivo favorito",
        f"{invitador} quiere compartir un moscow mule con {invitado}",
        f"{invitador} invita a {invitado} a probar su licor de frambuesa casero",
        f"{invitador} le sugiere a {invitado} que pruebe su cóctel de licor de mango",
        f"{invitador} quiere que {invitado} deguste su receta secreta de licor de pimienta",
        f"{invitador} piensa que un zombie sería perfecto para {invitado}",
        f"{invitador} invita a {invitado} a probar un poco de licor de guayaba",
        f"{invitador} quiere compartir un french 75 con {invitado}",
        f"{invitador} le sugiere a {invitado} que pruebe su licor de lavanda especial",
        f"{invitador} invita a {invitado} a degustar un cóctel con un toque de licor de cereza",
        f"{invitador} piensa que un margarita de tamarindo sorprendería a {invitado}",
        f"{invitador} le ofrece a {invitado} un poco de licor de sandía",
        f"{invitador} quiere que {invitado} pruebe su receta secreta de licor de granada",
    ]
    return random.choice(INVITAR_ALCOHOL)
